#ifndef TASK_SELECTION_H
#define TASK_SELECTION_H

#define TASK_DIMMING_IGROSENSORPUMP
#define TASK_KEYBOARD_TIME
#define TASK_LCD
#define TASK_EEPROM
#undef TASK_ETH_SD
#define TASK_BT


#define PERCENT_RAM_ALLOCATED(Perc)			  ((Perc * 8192)/100)


#define TASK_DIMMING_IGROSENSORPUMP_DELAY  1000	          
#define TASK_KEYBOARD_TIME_DELAY			 50
#define TASK_LCD_DELAY				    	500
#define TASK_EEPROM_DELAY	               1000
#define TASK_ETH_SD_DELAY			         50	
#define TASK_BT_DELAY				    	 50


/* STACK IN UINT16_T = 2 bytes - minima dimensione per task = 128 (FreeRTOSConfig.h) */

#ifdef TASK_DIMMING_IGROSENSORPUMP
#define TASK_DIMMING_IGROSENSORPUMP_STACK	128	        
#endif

#ifdef  TASK_KEYBOARD_TIME
#define TASK_KEYBOARD_TIME_STACK			128
#endif

#ifdef TASK_LCD
#define TASK_LCD_STACK				    	192
#endif

#ifdef TASK_EEPROM
#define TASK_EEPROM_STACK	                128
#endif

#ifdef  TASK_ETH_SD
#define TASK_ETH_SD_STACK			        192	
#endif

#ifdef  TASK_BT
#define TASK_BT_STACK				    	192
#endif
										
#define TASKS_STACK_SIZE				   (TASK_DIMMING_IGROSENSORPUMP_STACK+TASK_KEYBOARD_TIME_STACK+TASK_LCD_STACK+TASK_EEPROM_STACK+TASK_ETH_SD_STACK+TASK_BT_STACK)*2//2944
#define PROGRAM_RAM_OCCUPIED			   3289	
#define TOTAL_RAM_USED					   TASKS_STACK_SIZE+PROGRAM_RAM_OCCUPIED
										

#if (TOTAL_RAM_USED>PERCENT_RAM_ALLOCATED(80))
	#error OVER_80_PERCENT_RAM_USED
#endif


#define TASK_DIMMING_IGROSENSORPUMP_PRIORITY  1	          
#define TASK_KEYBOARD_TIME_PRIORITY			  3
#define TASK_LCD_PRIORITY					  1
#define TASK_EEPROM_PRIORITY	              0
#define TASK_ETH_SD_PRIORITY			      1
#define TASK_BT_PRIORITY					  3

#endif